import {
  FolderOpen, Save, Play, FlaskConical, LayoutGrid, Bug, Stethoscope,
  Puzzle, Code2, Download, Undo2, Redo2, Settings, ChevronRight,
  FileText, Link, CheckCircle, XCircle, AlertTriangle, Circle,
  Users, PanelLeftOpen, PanelRightOpen, ChevronDown, Search,
  X, Folder, ArrowRight, TestTube2, Plus, FilePlus2, Monitor,
} from 'lucide-react';

export const Icons = {
  folderOpen: FolderOpen,
  save: Save,
  play: Play,
  flask: FlaskConical,
  layout: LayoutGrid,
  bug: Bug,
  stethoscope: Stethoscope,
  puzzle: Puzzle,
  code: Code2,
  download: Download,
  undo: Undo2,
  redo: Redo2,
  settings: Settings,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  fileText: FileText,
  link: Link,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertTriangle: AlertTriangle,
  circle: Circle,
  users: Users,
  panelLeft: PanelLeftOpen,
  panelRight: PanelRightOpen,
  search: Search,
  x: X,
  folder: Folder,
  arrowRight: ArrowRight,
  testTube: TestTube2,
  plus: Plus,
  newFile: FilePlus2,
  monitor: Monitor,
};
